// 顶层 build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // Xposed API 仓库（部分版本需要）
        maven { url 'https://api.xposed.info/' }
    }
}
